import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/transaction.dart';
import '../models/budget.dart';
import '../models/app_user.dart';
import '../models/church.dart';

final _fmt = NumberFormat('#,##0.00');
final _dateFmt = DateFormat('MMM d, yyyy');

class FinancePdfService {
  static Future<void> generateAndPrintReport({
    required Church church,
    required AppUser user,
    required List<FinanceTransaction> transactions,
    required List<Budget> budgets,
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    final currency = church.currency;

    final filtered = transactions.where((t) {
      if (startDate != null && t.date.isBefore(startDate)) return false;
      if (endDate != null && t.date.isAfter(endDate)) return false;
      return true;
    }).toList();

    final income = filtered.where((t) => t.isIncome).fold<double>(0, (s, t) => s + t.amount);
    final expense = filtered.where((t) => !t.isIncome).fold<double>(0, (s, t) => s + t.amount);
    final balance = income - expense;

    final incomeByCategory = <String, double>{};
    for (final t in filtered.where((t) => t.isIncome)) {
      incomeByCategory[t.category] = (incomeByCategory[t.category] ?? 0) + t.amount;
    }

    final expenseByCategory = <String, double>{};
    for (final t in filtered.where((t) => !t.isIncome)) {
      expenseByCategory[t.category] = (expenseByCategory[t.category] ?? 0) + t.amount;
    }

    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(church.name,
                style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 4),
            pw.Text('Finance Report',
                style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
            pw.SizedBox(height: 2),
            pw.Text(
              startDate != null && endDate != null
                  ? '${_dateFmt.format(startDate)} - ${_dateFmt.format(endDate)}'
                  : 'All Transactions',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
            pw.Divider(),
          ],
        ),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by ${user.name} on ${_dateFmt.format(DateTime.now())}',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
            pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
                style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          ],
        ),
        build: (ctx) => [
          pw.Text('Summary', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            data: [
              ['Metric', 'Amount'],
              ['Total Income', '$currency ${_fmt.format(income)}'],
              ['Total Expenses', '$currency ${_fmt.format(expense)}'],
              ['Net Balance', '$currency ${_fmt.format(balance)}'],
              ['Transactions', '${filtered.length}'],
            ],
            cellStyle: const pw.TextStyle(fontSize: 10),
            headerStyle: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.green700),
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerRight,
            },
          ),
          pw.SizedBox(height: 20),
          pw.Text('Income Breakdown', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          if (incomeByCategory.isEmpty)
            pw.Text('No income recorded', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
          else
            pw.TableHelper.fromTextArray(
              data: [
                ['Category', 'Amount'],
                ...incomeByCategory.entries.map((e) => [e.key, '$currency ${_fmt.format(e.value)}']),
              ],
              cellStyle: const pw.TextStyle(fontSize: 10),
              headerStyle: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blue700),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerRight,
              },
            ),
          pw.SizedBox(height: 20),
          pw.Text('Expense Breakdown', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          if (expenseByCategory.isEmpty)
            pw.Text('No expenses recorded', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
          else
            pw.TableHelper.fromTextArray(
              data: [
                ['Category', 'Amount'],
                ...expenseByCategory.entries.map((e) => [e.key, '$currency ${_fmt.format(e.value)}']),
              ],
              cellStyle: const pw.TextStyle(fontSize: 10),
              headerStyle: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.red700),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerRight,
              },
            ),
          pw.SizedBox(height: 20),
          pw.Text('Transaction List', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          if (filtered.isEmpty)
            pw.Text('No transactions in this period', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
          else
            pw.TableHelper.fromTextArray(
              data: [
                ['Date', 'Type', 'Category', 'Description', 'Amount'],
                ...filtered.map((t) => [
                  _dateFmt.format(t.date),
                  t.isIncome ? 'Income' : 'Expense',
                  t.category,
                  t.description.isEmpty ? '-' : t.description,
                  '$currency ${_fmt.format(t.amount)}',
                ]),
              ],
              cellStyle: const pw.TextStyle(fontSize: 9),
              headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey700),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerLeft,
                3: pw.Alignment.centerLeft,
                4: pw.Alignment.centerRight,
              },
            ),
          if (budgets.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.Text('Budget Status', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              data: [
                ['Category', 'Period', 'Budgeted', 'Actual', 'Remaining'],
                ...budgets.map((b) {
                  final actual = filtered.where((t) =>
                    t.category == b.category &&
                    BudgetPeriod.key(t.date) == b.period &&
                    !t.isIncome
                  ).fold<double>(0, (s, t) => s + t.amount);
                  final remaining = b.allocatedAmount - actual;
                  return [
                    b.category,
                    b.period,
                    '$currency ${_fmt.format(b.allocatedAmount)}',
                    '$currency ${_fmt.format(actual)}',
                    '$currency ${_fmt.format(remaining)}',
                  ];
                }),
              ],
              cellStyle: const pw.TextStyle(fontSize: 9),
              headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.green700),
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerRight,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.centerRight,
              },
            ),
          ],
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => doc.save());
  }
}
